# Generated by Django 5.2.3 on 2025-06-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_donation_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('litres', 'Litres'), ('packets', 'Packets'), ('items', 'Items')], max_length=20, null=True),
        ),
    ]
