# Generated by Django 5.2.3 on 2025-07-12 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBankRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired')], default='active', max_length=10)),
                ('quantity_needed', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='authentication.foodbankprofile')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
