# Generated by Django 5.2.3 on 2025-07-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_foodbankrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('acknowledgement', 'Acknowledgement'), ('request', 'New Request'), ('system', 'System Update'), ('donation_received', 'Donation Received'), ('request_fulfilled', 'Request Fulfilled'), ('urgent_request', 'Urgent Request'), ('donation_pickup', 'Donation Pickup'), ('donation_delivered', 'Donation Delivered'), ('system_maintenance', 'System Maintenance'), ('new_donor', 'New Donor'), ('request_expiring', 'Request Expiring')], max_length=20),
        ),
    ]
