# Generated by Django 5.2.3 on 2025-08-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_donationallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='foodbank_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='authentication.foodbankrequest'),
        ),
    ]
