# Generated by Django 5.1.4 on 2025-09-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_donation_foodbank_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientprofile",
            name="consent_subsidized_goods",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="RecipientRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "quantity_unit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "delivery_method",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "foodbank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipient_requests",
                        to="authentication.foodbankprofile",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="authentication.recipientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField()),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="authentication.recipientprofile",
                    ),
                ),
            ],
        ),
    ]
