# Generated by Django for FoodBank Public Profile Feature

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_donation_foodbank_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbankprofile',
            name='about_text',
            field=models.TextField(blank=True, help_text='Tell donors about your food bank, mission, and impact', null=True),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Public contact email for donors', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Public contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year your food bank was established', null=True),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='header_photo',
            field=models.ImageField(blank=True, help_text='Header image for your public profile page', null=True, upload_to='foodbank/headers/'),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='mission_statement',
            field=models.TextField(blank=True, help_text="Your organization's mission statement", null=True),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text="Your organization's website", null=True),
        ),
        migrations.CreateModel(
            name='FoodBankGalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text="Photos showcasing your food bank's work and impact", upload_to='foodbank/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this photo prominently on your profile')),
                ('foodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='authentication.foodbankprofile')),
            ],
            options={
                'ordering': ['-is_featured', '-uploaded_at'],
            },
        ),
    ]
