# Generated by Django 5.2.6 on 2025-09-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_recipientprofile_consent_subsidized_goods_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationallocation",
            name="is_acknowledged",
            field=models.BooleanField(default=False),
        ),
    ]
