# Generated by Django 5.2.6 on 2025-09-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_donationallocation_is_acknowledged"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="is_allocated",
            field=models.BooleanField(default=False),
        ),
    ]
