# Generated by Django 5.2.6 on 2025-09-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_donation_is_allocated"),
        ("authentication", "0012_add_subsidized_market_price"),
    ]

    operations = []
