# Generated by Django 5.2.6 on 2025-09-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_merge_20250914_1017"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodbankrequest",
            name="donation_type",
            field=models.CharField(
                choices=[("food", "Food"), ("nonfood", "Non-Food")],
                default="food",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="foodbankrequest",
            name="recipient_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_foodbank_request",
                to="authentication.recipientrequest",
            ),
        ),
    ]
