# Generated by Django 5.2.6 on 2025-09-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_foodbankrequest_donation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
