# Generated by Django 5.2.6 on 2025-09-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_recipientrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientrequest",
            name="declined_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="declined_requests",
                to="authentication.foodbankprofile",
            ),
        ),
    ]
