# Generated by Django 5.2.3 on 2025-10-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_recipientrequest_declined_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbankprofile',
            name='service_type',
            field=models.CharField(choices=[('food', 'Food Only'), ('non_food', 'Non-Food Only'), ('both', 'Food and Non-Food')], default='both', help_text='What type of assistance does your food bank provide?', max_length=20),
        ),
    ]
