# Generated by Django 5.2.3 on 2025-10-05 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_add_service_type_to_foodbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbankprofile',
            name='additional_documents',
            field=models.FileField(blank=True, help_text='Upload any additional documentation (permits, certificates, etc.)', null=True, upload_to='foodbank/documents/'),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_foodbanks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='is_approved',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='foodbankprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True),
        ),
    ]
