# Generated by Django 5.2.3 on 2025-10-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_update_quantity_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbankrequest',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('litres', 'Litres'), ('packets', 'Packets'), ('items', 'Items'), ('bags', 'Bags'), ('boxes', 'Boxes'), ('cans', 'Cans'), ('bottles', 'Bottles'), ('pieces', 'Pieces'), ('units', 'Units'), ('tons', 'Tons'), ('grams', 'Grams'), ('ml', 'Millilitres'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
