# Generated by Django 5.2.7 on 2025-10-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_update_foodbank_request_quantity_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientrequest',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
