# Generated by Django 5.2.3 on 2025-10-06 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_update_foodbank_request_quantity_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='discussion_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Discussion'), ('in_progress', 'Discussion In Progress'), ('agreed', 'Terms Agreed'), ('declined', 'Declined')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_category',
            field=models.CharField(choices=[('food', 'Food'), ('non_food', 'Non-Food'), ('other', 'Other')], default='food', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_mode',
            field=models.CharField(choices=[('free', 'Free Donation'), ('subsidized', 'Subsidized Rate')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='other_description',
            field=models.TextField(blank=True, help_text="Description for 'other' type donations", null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='requires_discussion',
            field=models.BooleanField(default=False, help_text='Whether this donation requires discussion with recipient'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('item', 'Item'), ('money', 'Money'), ('subsidized', 'Subsidized Goods'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='DonationDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('in_progress', 'Discussion In Progress'), ('agreed', 'Terms Agreed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='authentication.donation')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_discussions', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_discussions', to='authentication.recipientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DonationDiscussionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='authentication.donationdiscussion')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
