# Generated by Django 5.2.7 on 2025-10-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_recipientrequest_delivery_method'),
        ('authentication', '0022_add_mpesa_fields'),
    ]

    operations = [
    ]
