# Generated by Django 5.2.7 on 2025-10-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_remove_paymenttransaction_net_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
