# Generated by Django 5.2.7 on 2025-10-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_alter_recipientrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbankrequest',
            name='linked_recipient_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.recipientrequest'),
        ),
        migrations.AddField(
            model_name='recipientrequest',
            name='linked_donor_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.foodbankrequest'),
        ),
    ]
