# Generated by Django 5.2.7 on 2025-11-03 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_supportmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='display_end_date',
            field=models.DateTimeField(blank=True, help_text='When to stop displaying (leave blank for 1 week from approval)', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='display_on_public',
            field=models.BooleanField(default=True, help_text='Display on public portal when approved'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='display_start_date',
            field=models.DateTimeField(blank=True, help_text='When to start displaying (leave blank for immediate)', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='impact_image',
            field=models.ImageField(blank=True, help_text='Upload a photo showing the impact of the help you received', null=True, upload_to='testimonials/impact/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this testimonial on the homepage'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_testimonials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(help_text='Share your story and the impact of the help you received'),
        ),
    ]
