# Generated by Django 5.2.7 on 2025-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_add_foodbank_testimonial_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='csr_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='csr_subcategory',
            field=models.CharField(blank=True, choices=[('philanthropy', 'Philanthropy'), ('volunteerism', 'Volunteerism'), ('environmental', 'Environmental/Sustainability'), ('humanitarian', 'Humanitarianism'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_category',
            field=models.CharField(choices=[('food', 'Food'), ('non_food', 'Non-Food'), ('monetary', 'Monetary'), ('csr', 'CSR'), ('other', 'Other')], default='food', max_length=20),
        ),
    ]
