# Generated by Django 5.2.7 on 2025-11-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_donation_csr_description_donation_csr_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_mode',
            field=models.CharField(choices=[('free', 'Free Donation'), ('subsidized', 'Subsidized Rate'), ('csr', 'CSR Initiative')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('item', 'Item'), ('money', 'Money'), ('subsidized', 'Subsidized Goods'), ('csr', 'CSR'), ('other', 'Other')], max_length=20),
        ),
    ]
