# Generated by Django 5.2.7 on 2025-11-14 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_alter_donation_donation_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('food', 'Food'), ('non_food', 'Non-Food')], max_length=20)),
                ('description', models.TextField(help_text="e.g., '100 bags of maize'")),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('litres', 'Litres'), ('packets', 'Packets'), ('items', 'Items'), ('bags', 'Bags'), ('boxes', 'Boxes'), ('cans', 'Cans'), ('bottles', 'Bottles'), ('pieces', 'Pieces'), ('units', 'Units'), ('tons', 'Tons'), ('grams', 'Grams'), ('ml', 'Millilitres'), ('other', 'Other')], max_length=20)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('both', 'Both Available')], max_length=20)),
                ('location', models.CharField(help_text='Delivery/pickup location', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('denied', 'Denied'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('additional_notes', models.TextField(blank=True, help_text='Notes added by foodbank', null=True)),
                ('time_of_request', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('foodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_requests', to='authentication.foodbankprofile')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_requests', to='authentication.recipientprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Management',
                'verbose_name_plural': 'Request Management',
                'ordering': ['-time_of_request'],
            },
        ),
    ]
