# Generated by Django 5.2.7 on 2025-11-16 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBankSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Free Trial (3 Months)'), ('monthly', 'Monthly Plan (KSH 2,000)'), ('yearly', 'Yearly Plan (KSH 10,000)')], default='trial', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial Period'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('trial_start_date', models.DateTimeField(auto_now_add=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foodbank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='authentication.foodbankprofile')),
            ],
            options={
                'verbose_name': 'Food Bank Subscription',
                'verbose_name_plural': 'Food Bank Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly Plan (KSH 2,000)'), ('yearly', 'Yearly Plan (KSH 10,000)')], max_length=20)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(help_text='M-Pesa code or bank reference number', max_length=100)),
                ('payment_date', models.DateField()),
                ('payment_evidence', models.ImageField(help_text='Upload screenshot of payment confirmation', upload_to='subscription_payments/')),
                ('notes', models.TextField(blank=True, help_text='Any additional information about the payment', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_info', 'Requires More Information')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to food bank)', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='authentication.foodbankprofile')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authentication.foodbanksubscription')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
