# Generated by Django 5.2.7 on 2025-11-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_foodbanksubscription_subscriptionpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title for identification', max_length=200)),
                ('image', models.ImageField(help_text='Upload background image', upload_to='landing_images/')),
                ('caption', models.TextField(blank=True, help_text='Optional caption or description')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers show first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this image on landing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Image',
                'verbose_name_plural': 'Landing Page Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
