# Generated by Django 5.2.7 on 2025-11-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_donation_decline_message_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='decline_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='quantity_fulfilled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestmanagement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('partial', 'Partially Fulfilled'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
