# Generated by Django 5.2.7 on 2025-11-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_requestmanagement_decline_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmanagement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('partial', 'Partially Fulfilled'), ('submitted', 'Submitted to Donors - Awaiting Donation'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
