# Generated by Django 5.2.7 on 2025-11-17 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_alter_requestmanagement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbankrequest',
            name='linked_recipient_request',
        ),
        migrations.RemoveField(
            model_name='foodbankrequest',
            name='recipient_request',
        ),
        migrations.AddField(
            model_name='foodbankrequest',
            name='original_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foodbank_request_created', to='authentication.requestmanagement'),
        ),
    ]
