# Generated by Django 5.2.7 on 2025-11-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_remove_foodbankrequest_linked_recipient_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='assigned_foodbank',
            field=models.ForeignKey(blank=True, help_text='Foodbank that accepted the anonymous request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='authentication.foodbankprofile'),
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestmanagement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Foodbank'), ('fulfilled', 'Fulfilled'), ('partial', 'Partially Fulfilled'), ('submitted', 'Submitted to Donors - Awaiting Donation'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
