# Generated by Django 5.2.7 on 2025-11-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_requestmanagement_assigned_foodbank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmanagement',
            name='foodbank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_requests', to='authentication.foodbankprofile'),
        ),
    ]
