# Generated by Django 5.2.7 on 2025-11-19 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_adminloginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique admin registration code', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for this code', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code can be used for registration')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this code has been used')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this code was last used', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_admin_codes', to=settings.AUTH_USER_MODEL)),
                ('last_used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_admin_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Registration Code',
                'verbose_name_plural': 'Admin Registration Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
