# Generated by Django 5.2.7 on 2025-11-20 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0043_admincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="Share your experience as a donor and the impact you've witnessed")),
                ('impact_image', models.ImageField(blank=True, help_text='Upload a photo related to your donation experience or impact witnessed', null=True, upload_to='testimonials/donor/')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this testimonial on the homepage')),
                ('display_on_public', models.BooleanField(default=True, help_text='Display on public portal when approved')),
                ('display_start_date', models.DateTimeField(blank=True, help_text='When to start displaying (leave blank for immediate)', null=True)),
                ('display_end_date', models.DateTimeField(blank=True, help_text='When to stop displaying (leave blank for 1 week from approval)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='authentication.donorprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_donor_testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Testimonial',
                'verbose_name_plural': 'Donor Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
