# Generated by Django 5.2.7 on 2025-11-20 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_donortestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSupportDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount donated in KES', max_digits=10)),
                ('payment_proof', models.ImageField(help_text='Upload screenshot or proof of payment', upload_to='system_support_payments/')),
                ('transaction_reference', models.CharField(blank=True, help_text='M-Pesa code or bank reference (optional)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the donation', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to donor)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_support_donations', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_system_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Support Donation',
                'verbose_name_plural': 'System Support Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
