# Generated by Django 5.2.7 on 2025-11-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_accountdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.donation'),
        ),
    ]
