# Generated by Django 5.2.7 on 2025-11-20 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_requestmanagement_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='subsidized_responded_by',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'RECIPIENT'}, related_name='subsidized_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
