# Generated by Django 5.2.7 on 2025-11-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_systemsupportdonation'),
        ('authentication', '0046_donation_subsidized_responded_by'),
    ]

    operations = [
    ]
