# Generated by Django 5.2.7 on 2025-11-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0047_merge_20251121_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('partial', 'Partial')], max_length=20)),
                ('partial_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='authentication.donation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.recipientprofile')),
            ],
            options={
                'unique_together': {('donation', 'recipient')},
            },
        ),
    ]
