# Generated by Django 5.2.7 on 2025-11-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0048_donationresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='accepted_by_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_subsidized_donations', to='authentication.recipientprofile'),
        ),
    ]
