# Generated by Django 5.2.7 on 2025-11-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0049_donation_accepted_by_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageImage',
        ),
    ]
