# Generated by Django 5.2.7 on 2025-11-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0049_donation_accepted_by_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='declined_by_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_subsidized_donations', to='authentication.recipientprofile'),
        ),
    ]
