# Generated by Django 5.2.7 on 2025-11-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0050_delete_landingpageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationdiscussion',
            name='recipient',
        ),
        migrations.AddField(
            model_name='donationdiscussion',
            name='foodbank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodbank_discussions', to='authentication.foodbankprofile'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='requires_discussion',
            field=models.BooleanField(default=False, help_text='Whether this donation requires discussion with foodbank'),
        ),
    ]
