# Generated by Django 5.2.7 on 2025-11-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0050_donation_declined_by_recipient'),
        ('authentication', '0051_remove_donationdiscussion_recipient_and_more'),
    ]

    operations = [
    ]
