# Generated by Django 5.2.7 on 2025-11-21 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0052_merge_20251121_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationdiscussion',
            name='foodbank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foodbank_discussions', to='authentication.foodbankprofile'),
            preserve_default=False,
        ),
    ]
