# Generated by Django 5.2.7 on 2025-11-23 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0053_alter_donationdiscussion_foodbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News title or headline', max_length=200)),
                ('content', models.TextField(help_text='News content or description')),
                ('image', models.ImageField(help_text='Upload graphic or image for the news', upload_to='news_section/')),
                ('is_active', models.BooleanField(default=True, help_text='Display this news on the landing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Section',
                'verbose_name_plural': 'News Sections',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
