# Generated by Django 5.2.7 on 2025-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0054_newssection'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
