# Generated by Django 5.2.7 on 2025-11-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0055_donorprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='foodbank_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_requests', to='authentication.foodbankrequest'),
        ),
    ]
