# Generated by Django 5.2.7 on 2025-11-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0055_donorprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], help_text='Payment method for monetary donations', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='Upload payment receipt', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_reference_number',
            field=models.CharField(blank=True, help_text='Payment reference number', max_length=100, null=True),
        ),
    ]
