# Generated by Django 5.2.7 on 2025-11-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_donation_payment_method_donation_payment_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_receipt',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_reference_number',
        ),
    ]
