# Generated by Django 5.2.7 on 2025-11-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_requestmanagement_foodbank_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbankrequest',
            name='quantity_fulfilled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
