# Generated by Django 5.2.7 on 2025-11-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0057_foodbankrequest_quantity_fulfilled'),
        ('authentication', '0057_remove_donation_payment_method_and_more'),
    ]

    operations = [
    ]
