# Generated by Django 5.2.7 on 2025-11-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0058_merge_20251125_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='acknowledged_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestmanagement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Foodbank'), ('fulfilled', 'Fulfilled'), ('partial', 'Partially Fulfilled'), ('acknowledged', 'Acknowledged by Recipient'), ('submitted', 'Submitted to Donors - Awaiting Donation'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
