# Generated by Django 5.2.7 on 2025-11-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0059_requestmanagement_acknowledged_by_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbankrequest',
            name='custom_unit',
            field=models.CharField(blank=True, help_text="Custom unit when 'Other' is selected", max_length=50, null=True),
        ),
    ]
