# Generated by Django 5.2.7 on 2025-11-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0060_foodbankrequest_custom_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='custom_unit',
            field=models.CharField(blank=True, help_text="Custom unit when 'Other' is selected", max_length=50, null=True),
        ),
    ]
