# Generated by Django 5.2.7 on 2025-12-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0061_requestmanagement_custom_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_mode',
            field=models.CharField(choices=[('free', 'Free Donation'), ('subsidized', 'Subsidized Rate'), ('csr', 'CSR Initiative'), ('discussion', 'Requires Discussion')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestmanagement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Foodbank'), ('fulfilled', 'Fulfilled'), ('partial', 'Partially Fulfilled'), ('acknowledged', 'Acknowledged by Recipient'), ('submitted', 'Submitted to Donors - Awaiting Donation'), ('donation_received', 'Donor donated Awaiting Acceptance'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
