# Generated by Django 5.2.7 on 2025-12-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0062_alter_donation_donation_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmanagement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Foodbank'), ('awaiting_recipient', 'Awaiting Recipient'), ('fulfilled', 'Fulfilled'), ('partial', 'Partially Fulfilled'), ('acknowledged', 'Acknowledged by Recipient'), ('submitted', 'Submitted to Donors - Awaiting Donation'), ('donation_received', 'Donated awaiting approval'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
