# Generated by Django 5.2.7 on 2025-12-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0063_add_awaiting_recipient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='agreed_clause',
            field=models.TextField(blank=True, help_text='Agreed terms/clause for CSR and Other donations after discussion', null=True),
        ),
    ]
