# Generated by Django 5.2.7 on 2025-12-12 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0064_add_agreed_clause_to_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnspecifiedDonationManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodbank_status', models.CharField(choices=[('pending_foodbank', 'Pending Foodbank Review'), ('accepted_by_foodbank', 'Accepted by Foodbank'), ('declined_by_foodbank', 'Declined by Foodbank')], default='pending_foodbank', max_length=30)),
                ('foodbank_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('foodbank_decline_reason', models.TextField(blank=True, null=True)),
                ('recipient_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending_recipient', 'Available for Recipients'), ('accepted_by_recipient', 'Accepted by Recipient'), ('declined_by_recipient', 'Declined by Recipient'), ('received', 'Received by Recipient')], default='not_applicable', max_length=30)),
                ('recipient_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_decline_reason', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_unspecified_donations', to='authentication.recipientprofile')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unspecified_management', to='authentication.donation')),
            ],
            options={
                'verbose_name': 'Unspecified Donation Management',
                'verbose_name_plural': 'Unspecified Donation Management',
                'ordering': ['-created_at'],
            },
        ),
    ]
