# Generated by Django 5.2.7 on 2025-12-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_update_nonfood_to_non_food'),
        ('authentication', '0066_alter_donation_amount_and_more'),
    ]

    operations = [
    ]
