# Generated by Django 5.2.7 on 2025-12-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0067_merge_20251219_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbankrequest',
            name='donation_type',
            field=models.CharField(choices=[('food', 'Food'), ('non_food', 'Non-Food')], default='food', max_length=20),
        ),
    ]
