# Generated by Django 6.0 on 2025-12-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0067_merge_20251219_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodbankrequest',
            name='donation_type',
            field=models.CharField(choices=[('food', 'Food'), ('non_food', 'Non-Food')], default='food', max_length=20),
        ),
    ]
