# Generated by Django 6.0 on 2025-12-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0068_alter_foodbankrequest_donation_type'),
        ('authentication', '0068_requestmanagement_due_date_and_more'),
    ]

    operations = [
    ]
