# Generated by Django 6.0 on 2025-12-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0069_merge_20251223_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmanagement',
            name='due_date',
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='awaiting_donors',
            field=models.BooleanField(default=False),
        ),
    ]
