# Generated by Django 6.0 on 2026-01-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0070_remove_requestmanagement_due_date_and_more'),
    ]

    operations = [
    ]
