# Generated by Django 6.0 on 2025-12-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0070_remove_requestmanagement_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='request_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='authentication.requestmanagement'),
        ),
    ]
