# Generated by Django 6.0 on 2025-12-24 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0071_donation_request_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbankrequest',
            name='linked_request_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_requests', to='authentication.requestmanagement'),
        ),
    ]
