# Generated by Django 5.2.7 on 2026-01-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0072_foodbankrequest_linked_request_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='request_category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('non_food', 'Non-Food')], max_length=20, null=True),
        ),
    ]
