# Generated by Django 5.2.7 on 2026-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0073_requestmanagement_request_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='custom_quantity_unit',
            field=models.CharField(blank=True, help_text="Custom unit when 'Other' is selected", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='custom_subsidized_quantity_unit',
            field=models.CharField(blank=True, help_text="Custom unit when 'Other' is selected", max_length=50, null=True),
        ),
    ]
