# Generated by Django 5.2.7 on 2026-01-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0074_donation_custom_quantity_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='custom_quantity_unit',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='custom_subsidized_quantity_unit',
        ),
    ]
