# Generated by Django 5.2.7 on 2026-01-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0075_remove_donation_custom_quantity_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='csr_custom_subcategory',
            field=models.CharField(blank=True, help_text="Custom CSR subcategory label when 'Other' is selected", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity_unit',
            field=models.CharField(blank=True, help_text='Unit label for quantity (e.g., boxes, kits)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='subsidized_quantity_unit',
            field=models.CharField(blank=True, help_text='Unit label for subsidized quantity', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unspecifieddonationmanagement',
            name='recipient_status',
            field=models.CharField(choices=[('not_applicable', 'Not Claimed'), ('pending_recipient', 'Available for Recipients'), ('accepted_by_recipient', 'Accepted by Recipient'), ('declined_by_recipient', 'Declined by Recipient'), ('received', 'Received by Recipient')], default='not_applicable', max_length=30),
        ),
    ]
