# Generated by Django 5.2.7 on 2026-01-13 04:23

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def backfill_foodbankrequest_deadline(apps, schema_editor):
    FoodBankRequest = apps.get_model('authentication', 'FoodBankRequest')

    qs = FoodBankRequest.objects.filter(deadline__isnull=True)

    to_update = []
    now = timezone.now()

    for req in qs.iterator():
        base = req.created_at or now
        req.deadline = base + timedelta(days=30)
        to_update.append(req)

    if to_update:
        FoodBankRequest.objects.bulk_update(to_update, ['deadline'])


def noop_reverse(apps, schema_editor):
    # Data migration is not safely reversible.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0076_donation_csr_custom_subcategory_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_foodbankrequest_deadline, noop_reverse),
    ]
