# Generated by Django 5.2.7 on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0078_supportmessagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='donortestimonial',
            name='public_website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
