# Generated by Django 5.2.7 on 2026-01-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0071_systemsupportdonation_payment_method'),
        ('authentication', '0079_donortestimonial_public_website_url'),
    ]

    operations = [
    ]
