# Generated by Django 5.2.7 on 2026-01-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0080_merge_20260121_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_code',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
