# Generated by Django 5.2.7 on 2026-01-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0081_donation_donation_code'),
    ]

    operations = [
    ]
