# Generated by Django 5.2.7 on 2026-02-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0082_foodbankrequest_delivery_method_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='allocation_source_type',
            field=models.CharField(blank=True, choices=[('subsidized', 'Subsidized'), ('monetary', 'Monetary'), ('free_goods', 'Free Goods')], help_text='Donation type selected when fulfilling via available donations', max_length=20, null=True),
        ),
    ]
