# Generated by Django 5.2.7 on 2026-02-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0083_requestmanagement_allocation_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationallocation',
            name='request_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_allocations', to='authentication.requestmanagement'),
        ),
    ]
