# Generated by Django 5.2.7 on 2026-02-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0084_donationallocation_request_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmanagement',
            name='allocation_source_type',
        ),
    ]
