# Generated by Django 5.2.7 on 2026-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0085_remove_requestmanagement_allocation_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='declined_by_foodbank',
            field=models.BooleanField(default=False, help_text="True when a foodbank declined a donor offer so recipients shouldn't see it as declined"),
        ),
    ]
