# Generated by Django 5.2.7 on 2026-02-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0086_requestmanagement_declined_by_foodbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmanagement',
            name='declined_by_foodbank',
        ),
    ]
