# Generated by Django 5.2.7 on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0087_remove_requestmanagement_declined_by_foodbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationallocation',
            name='declined_by_recipient',
            field=models.BooleanField(default=False, help_text='True when recipient declined this allocation (row stays visible with Declined status)'),
        ),
    ]
