# Generated by Django 5.2.7 on 2026-02-08 10:13

from django.db import migrations, models


def seed_quantity_units(apps, schema_editor):
    QuantityUnit = apps.get_model('authentication', 'QuantityUnit')
    default_units = [
        ('kg', 'Kilograms'),
        ('litres', 'Litres'),
        ('packets', 'Packets'),
        ('items', 'Items'),
        ('bags', 'Bags'),
        ('boxes', 'Boxes'),
        ('cans', 'Cans'),
        ('bottles', 'Bottles'),
        ('pieces', 'Pieces'),
        ('units', 'Units'),
        ('tons', 'Tons'),
        ('grams', 'Grams'),
        ('ml', 'Millilitres'),
        ('other', 'Other'),
    ]
    for code, label in default_units:
        if not QuantityUnit.objects.filter(code=code).exists():
            QuantityUnit.objects.create(code=code, label=label)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0087_remove_requestmanagement_declined_by_foodbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(seed_quantity_units, migrations.RunPython.noop),
    ]
