# Generated by Django 5.2.7 on 2026-02-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0088_donationallocation_declined_by_recipient'),
        ('authentication', '0088_quantityunit'),
    ]

    operations = [
    ]
