# Generated by Django 5.2.7 on 2026-02-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0089_merge_20260208_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationallocation',
            name='declined_by_recipient',
            field=models.BooleanField(default=False, help_text='True when recipient declined this allocation'),
        ),
    ]
