# Generated by Django 5.2.7 on 2026-02-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0090_alter_donationallocation_declined_by_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationallocation',
            name='declined_by_recipient',
            field=models.BooleanField(default=False, help_text='True when recipient declined this allocation (row stays visible with Declined status)'),
        ),
    ]
