# Generated by Django 5.2.7 on 2026-02-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0091_alter_donationallocation_declined_by_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbankrequest',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('both', 'Both Available')], max_length=20, null=True),
        ),
    ]
