# Generated by Django 5.2.7 on 2026-03-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0092_foodbankrequest_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientrequest',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
