# Generated by Django 5.2.7 on 2026-03-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0093_alter_recipientrequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbankrequest',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
