# Generated by Django 5.2.7 on 2026-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0094_alter_foodbankrequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbankrequest',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
